# Generated by Django 5.2 on 2025-05-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagonostic_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
