# Generated by Django 5.1.7 on 2025-04-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='doc_img/'),
        ),
    ]
